# Build script for the snake multiplayer

version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
    pre_build:
        commands:
            - echo `date` - Starting build!
    build:
        commands:
            - npm install
            - npm ci
    post_build:
        commands:
            # Create the staging and production bundles for node server
            - echo `date` - Build completed!
artifacts:
  files:
    - '**/*'